server:
  port: 8763
spring:
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true # ¿ªÆôÈÛ¶ÏÆ÷