server:
  port: 8767
spring:
  application:
    name: service-config
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-config?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      label: master
      server:
        jdbc:
          sql: SELECT key1, value1 from config_properties where APPLICATION=? and PROFILE=? and LABEL=?
      uri: http://localhost:8767
      profile: dev
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/