server:
  port: 8766
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false # true 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
      routes:
      - id: service-feign
        uri: lb://service-feign # /info必须使用http进行转发，lb代表从注册中心获取服务
        filters:
        - StripPrefix=1
        predicates:
        - Path=/feign/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true